### ISSUE TITLE
acd mount not seeing random files after sync.

### ISSUE THREAD

**Issue by jxer** [yadayada/acd_cli#493] opened 2016-11-22 03:02 UTC
troubleshooting rclone, found a issue with acdcli
https://github.com/ncw/rclone/issues/837

https://gyazo.com/323684a89050ef6cd22af05a77d25920

after extensive debugging the issue is NOT with rclone, it has to do with the acdcli mount, even when dropping the acd mount and issuing a sync, random files would not appear after a remount.

after troubleshooting through encryption (NOT FUN), it was found that rclone saw the file.

after multiple attempts to resync and not finding the random file missing. another computer was setup with acd mount and with a fresh db etc, shockingly all the files showed up on the acd mount,

sync again on the original computer, still can't see it,

delete everything in .cache/acd cli, minus the oauth_data file and resync and presto, everything shows up!

**Comment by yadayada** [comment] 2016-11-22 05:40
This is a duplicate of #464.

**Closed by yadayada** 2016-11-22 05:40 UTC
Labels: duplicate
