### ISSUE TITLE
Improving directory listing (getattr()) performance

### ISSUE THREAD

**Issue by msh100** [yadayada/acd_cli#97] opened 2015-07-23 22:51 UTC
I have noticed directory listing and generally `getattr()` performance on `acd_cli` is quite poor.

```bash
$ time tree $LOCAL > /dev/null
real    0m2.093s
user    0m0.252s
sys     0m0.044s
$ time tree $ACD > /dev/null
real    1m10.940s
user    0m0.112s
sys     0m0.152s
```

`$LOCAL` is a local EXT4 filesystem. Both `$LOCAL` and `$ACD` have the same files and structure.

During the `tree` period, the `acd_cli` mount is also at 100% CPU. I understand that all the data is being stored locally (once fetched from an `acd_cli sync`) so believe the performance can be greatly improved. 

I understand it will never match the EXT4 performance, however shouldn't be this resource intensive/inefficient.

**Comment by yadayada** [comment] 2015-07-24 17:00
It seems the path resolution, which is done fully for each node, is excessive and slow. I can't think of a trivial way to rectify this.

**Comment by msh100** [comment] 2015-07-24 17:51
May be a long shot but I don't suppose using something other than SQLite would improve things? (I am not too sure how much of the inefficiency is caused because of SQLite)

**Comment by yadayada** [comment] 2015-07-24 18:27
I was thinking more along the lines of adding a path cache and changing the way path resolution is done for FUSE.

What is the output of ``time acdcli tree`` for your path?

**Comment by msh100** [comment] 2015-07-24 18:28
```
real    0m3.057s
user    0m0.890s
sys     0m0.082s
```

**Comment by msh100** [comment] 2015-07-24 18:29
A more fair test (STDOUT to /dev/null)

```

real    0m0.855s
user    0m0.781s
sys     0m0.048s
```

**Comment by msh100** [comment] 2015-08-23 15:17
Sorry I have been a bit inactive lately. A week or so ago you committed to `dev` with some improvements, here are my test results.

```
$ time tree $DIR > /dev/null
real    2m15.692s
user    0m0.200s
sys     0m0.288s
$ # Updated acd_cli to dev branch
$ fusermount -u $DIR
$ acd_cli mount $DIR
$ time tree $DIR > /dev/null
real    0m40.057s
user    0m0.172s
sys     0m0.192s
```

**Comment by Timdawson264** [comment] 2015-08-29 07:00
I wrote some C that  directly access the sqlite db. its pretty fast but its still a little buggy and read only.
we could point libfuse to acdfuse_c for getattr and readir on compatible platforms. see the repo for some benchmarks

https://github.com/Timdawson264/acdfuse_c

cheers

**Comment by yadayada** [comment] 2015-08-29 10:52
I always seem to get very different timing results...

@Timdawson264 Looks promising. I got a decrease to about 1/6th for a tree listing in comparison to the acd_cli FUSE mount.
It also seems reasonable to use a lower-level language for the FUSE implementation, especially for the file transfers.

Since you already came up with some raw SQL statements, I'll look into it.

**Comment by msh100** [comment] 2015-08-29 12:49
@Timdawson264 that's fantastic. I'll be sure to check it out shortly.

**Comment by saqebakhter** [comment] 2015-10-01 18:56
+1

**Comment by HazCod** [comment] 2015-10-05 11:16
+1

**Comment by yadayada** [comment] 2015-10-05 15:27
So far, nobody seems to care enough to implement it.

I had written a simple non-invalidating path cache test class some time ago, see
https://gist.github.com/yadayada/ec60ec81f1e6f6c5cbcd

The speed-up is about 10x for me.

**Comment by saqebakhter** [comment] 2015-10-05 15:31
Is that implemented in master.?

**Comment by yadayada** [comment] 2015-10-05 15:38
No, it's not implemented anywhere. It was meant as a drop-in replacement for the node cache in FUSE to evaluate the possible speed-up.

**Comment by shushry** [comment] 2015-10-12 21:00
I'm definitely interested in it - but I don't possess the coding skills.   Who wants a shiny cold six-pack to do this?   Performance boosting directory enumeration would be most helpful.

**Comment by Slennox** [comment] 2015-10-12 21:28
Copying files also is like 10x faster using acd_cli upload than acd_cli mount.

acd_cli CPU usage goes to the roof when copying large files to the mounted filesystem. Anybody else seeing this?

**Comment by shushry** [comment] 2015-10-12 21:40
I can confirm that performance @Slennox.  I use the upload function currently to push content vs a standard filesystem operation like mv or copy.    On that note, mv operations in place (i.e, renaming a file) are quick.

**Comment by Slennox** [comment] 2015-10-12 21:54
Yeah, the problem is that in my use case (deluge, move completed torrents) the easy solution is to rely on standard filesystem access.

**Comment by shushry** [comment] 2015-10-12 22:01
@Slennox - to get around similar issues with the performance, I'm currently doing such things on local disk, and then I have a shell script job that pushes content with the upload function of acd_cli

**Comment by Slennox** [comment] 2015-10-12 22:12
@shushry: I'm also looking into that. In fact, that should be the solution I'm looking for. ACD's object storage isn't designed to work well with torrent downloading. However torrent seeding should be perfectly fine (just some tweaking required with send buffers on torrent client side), The idea is just to download torrents to local disk and then upload them to ACD, BUT keep seeding them from there.

**Comment by Slennox** [comment] 2015-10-13 21:31
@shushry, tweaking WRITE_BUFFER_SZ in acd_fuse.py to 2 ** 12 (4k) works for me. Now I can max out my 100 Mbps uplink to ACD through fuse.

@yadayada I think you've adjusting that buffer in latest comits (see https://github.com/yadayada/acd_cli/issues/130). Do you see any downside on increasing this write buffer? CPU usage it's still 100% though.

**Comment by HazCod** [comment] 2015-10-14 06:53
@shushry @Slennox I have put such a script I'm using in a gist; https://gist.github.com/HazCod/97b64f048158e165a25a

**Comment by Slennox** [comment] 2015-10-14 20:31
@HazCod thanks for sharing!

I'm still looking into the performance issue and found out that the standard cp/mv through fuse are indeed as fast as acd_cli upload. The problem is the encfs layer I use between them: local -> encfs fuse -> acd fuse... 

Some tests copying a dummy 256 MB file:

cp to acd fuse (maxes out my 100 Mbps uplink)
```
slennox@vps:~$ time cp test .acd/

real	0m28.271s
user	0m0.008s
sys	0m1.652s
```

acd_cli upload (maxes out my 100 Mbps uplink)
```
slennox@vps:~$ time acd_cli upload test /
[#########################] 100.0% of  256MiB  1/1    2.4MB/s       0s

real	0m26.659s
user	0m4.708s
sys	0m1.348s
```

cp to encfs fuse -> local SSD (just to discard CPU bottleneck)
```
slennox@vps:~$ time cp test to_upload/

real	0m3.189s
user	0m0.012s
sys	0m0.768s
```

cp to encfs fuse -> acd fuse: roughly 5 Mbps...

I'm trying to tweak encfs fuse or at least the way the OS links encfs fuse with acd fuse considering the fact that ciphering process shouldn't have that huge performance impact. I would be more than happy if somebody can shed light on this.

**Comment by saqebakhter** [comment] 2015-10-14 21:26
@slennox I noticed the same thing with encfs and acdfuse but was not able
to figure out how to fix it. Let me know if you figure it out...

**Comment by Slennox** [comment] 2015-10-15 20:19
@saqebakhter debugging acd_cli mount you can see that encfs sends the information much more fragmented than sending it directly, and given the high latency of ACD (compared to a local storage) that results and a huge performance impact.

cp test file to acd_fuse
```
15-10-14 23:41:58.557 [DEBUG] [acdcli.acd_fuse] - -> write /test (4096, 0, 2)
15-10-14 23:41:58.561 [DEBUG] [acdcli.acd_fuse] - <- write 4096
15-10-14 23:41:58.561 [DEBUG] [acdcli.acd_fuse] - -> write /test (4096, 4096, 2)
15-10-14 23:41:58.562 [DEBUG] [acdcli.acd_fuse] - <- write 4096
```

cp test file to encfs fuse -> acd fuse (Hw8S3tt6qK8DnOvekXJbIdtA is the same encrypted test file)
```
15-10-15 00:52:55.923 [DEBUG] [acdcli.acd_fuse] - -> write /Hw8S3tt6qK8DnOvekXJbIdtA (8, 0, 4)
15-10-15 00:52:55.926 [DEBUG] [acdcli.acd_fuse] - <- write 8
15-10-15 00:52:55.926 [DEBUG] [acdcli.acd_fuse] - -> getxattr /Hw8S3tt6qK8DnOvekXJbIdtA ('security.capability',)
15-10-15 00:52:55.928 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
15-10-15 00:52:55.928 [DEBUG] [acdcli.acd_fuse] - -> write /Hw8S3tt6qK8DnOvekXJbIdtA (1024, 8, 4)
15-10-15 00:52:55.929 [DEBUG] [acdcli.acd_fuse] - <- write 1024
15-10-15 00:52:55.929 [DEBUG] [acdcli.acd_fuse] - -> getxattr /Hw8S3tt6qK8DnOvekXJbIdtA ('security.capability',)
15-10-15 00:52:55.931 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
15-10-15 00:52:55.931 [DEBUG] [acdcli.acd_fuse] - -> write /Hw8S3tt6qK8DnOvekXJbIdtA (1024, 1032, 4)
15-10-15 00:52:55.931 [DEBUG] [acdcli.acd_fuse] - <- write 1024
15-10-15 00:52:55.931 [DEBUG] [acdcli.acd_fuse] - -> getxattr /Hw8S3tt6qK8DnOvekXJbIdtA ('security.capability',)
15-10-15 00:52:55.933 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
15-10-15 00:52:55.933 [DEBUG] [acdcli.acd_fuse] - -> write /Hw8S3tt6qK8DnOvekXJbIdtA (1024, 2056, 4)
15-10-15 00:52:55.934 [DEBUG] [acdcli.acd_fuse] - <- write 1024
15-10-15 00:52:55.934 [DEBUG] [acdcli.acd_fuse] - -> getxattr /Hw8S3tt6qK8DnOvekXJbIdtA ('security.capability',)
15-10-15 00:52:55.936 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
15-10-15 00:52:55.936 [DEBUG] [acdcli.acd_fuse] - -> write /Hw8S3tt6qK8DnOvekXJbIdtA (1016, 3080, 4)
15-10-15 00:52:55.936 [DEBUG] [acdcli.acd_fuse] - <- write 1016
15-10-15 00:52:55.936 [DEBUG] [acdcli.acd_fuse] - -> write /Hw8S3tt6qK8DnOvekXJbIdtA (8, 4096, 4)
15-10-15 00:52:55.937 [DEBUG] [acdcli.acd_fuse] - <- write 8
```

What I don't know is how to force encfs to write larger blocks to the encrypted filesystem (which is ACD).

@yadayada do you have an idea why this different behavior on writing to storage?

**Comment by shushry** [comment] 2015-10-15 21:25
Feels like this issue is getting into the weeds just a bit - the original post regarded directory listing performance, but now we're adding encfs on top of it.   I'll leave it to @yadayada  if this needs a separate thread. 

That said - what I'm doing is encrypting data on local disk (with a second encfs mount), and then pushing pre-encrypted data to acd.   Reading it back seems to be just fine at least for my needs.

I'm finding it hilarious that we're all using this for what looks to be very similar purposes :)

**Comment by tuapuikia** [comment] 2015-11-25 03:33
The problem seem to only happen if your directory have > 2k sub directory. It took me 9minutes  to perform ls with 2.4k directory inside.

**Comment by tuapuikia** [comment] 2015-11-25 04:40
if I run ls -f, the listing took 0.1 seconds to complete. But without timestamp and attr on the display.

**Comment by ratherDashing** [comment] 2015-11-25 17:13
You can increase the performance of encfs by tweaking the block size in the xml file:

<blockSize>1024</blockSize>

I was able to increase it to 4k and got better performance but it was still very crummy.  Over 4k encfs has an issue.  It is due to this fact:

http://linux.die.net/man/1/encfs

Filesystem Block Size
    This is the size (in bytes) that EncFS deals with at one time. Each block gets its own initialization vector and is encoded in the cipher's cipher-block-chaining mode. A partial block at the end of a file is encoded using a stream mode to avoid having to store the filesize somewhere.

    Having larger block sizes reduces the overhead of EncFS a little, but it can also add overhead if your programs read small parts of files. In order to read a single byte from a file, the entire block that contains that byte must be read and decoded, so a large block size adds overhead to small requests. With write calls it is even worse, as a block must be read and decoded, the change applied and the block encoded and written back out.

    The default is 512 bytes as of version 1.0. It was hard coded to 64 bytes in version 0.x, which was not as efficient as the current setting for general usage. 

So you can see why writes are terrible.  My fear is unless the fuse file system can buffer these writes in to more manageable blocks like 512k or 1MB this issue is with the encfs block size

**Comment by yadayada** [comment] 2015-12-07 22:24
I rewrote some queries as approximations using the sqlite3 module directly, available in the  [getattr](https://github.com/yadayada/acd_cli/tree/getattr) branch.

The speed-up is 8x for me vs. 3.5x using acdfuse_c, but the comparison isn't exactly fair.

**Comment by Slennox** [comment] 2015-12-08 01:22
@ratherDashing Since kernel 3.15, fuse has indeed a writeback cache functionality, but unfortunately the interface isn't merged yet to latest libfuse releases, it's only available on git repo (I don't know thy). I managed to recompile libfuse from the git repo on my system and was able to mount a fuse filesystem with writeback_cache policy. But when I tried it on encfs, an I/O error occurred on every write attempt. I 

I agree that a larger block size for encfs indeed helps, I tested it an write throughput increases. But a writeback cache is still needed to achieve good performance. See http://sourceforge.net/p/fuse/mailman/message/32034641/

**Comment by tuapuikia** [comment] 2015-12-08 02:20
I think we should focus on improve the file listing in normal fuse mount before move the encryptfs. We have different ticket for it.
https://github.com/yadayada/acd_cli/issues/189

**Comment by msh100** [comment] 2015-12-08 18:00
Thanks for all your hard work on this @yadayada, it's much appreciated. My test results are consistent-ish with yours:

```
user@host:~$ # UNMOUNT
user@host:~$ # REMOUNT
user@host:~$ time tree $DIR > /dev/null

real    3m22.314s
user    0m0.256s
sys     0m0.492s
user@host:~$ # UNMOUNT
user@host:~$ # update acd_cli to getattr branch and force resync of nodes
user@host:~$ # REMOUNT
user@host:~$ time tree $DIR > /dev/null

real    0m37.449s
user    0m0.228s
sys     0m0.424s
```

I am going to resume using this mount, I will let you know if I encounter any issues.

Also: Other people please keep this issue on topic, don't pollute issues with unrelated issues - it's kind of rude.

**Comment by msh100** [comment] 2015-12-08 18:04
Although, reading files they are 0 bytes/empty. So I wouldn't say this is usable yet :smile:

**Comment by yadayada** [comment] 2015-12-08 18:20
>Although, reading files they are 0 bytes/empty

I haven't yet pushed my updates for that. 

Putting an index on the names column further sped up the raw SQL queries about 3x. Now, I've gone from 5.5 minutes, initially, to about 15 seconds for a tree operation.

**Comment by msh100** [comment] 2015-12-08 18:22
Fantastic! Let me know when you have something to test, I'd love to give it a go.

**Comment by shushry** [comment] 2015-12-10 20:26
I just pulled the getattr branch and WOW what a difference in listing performance!

**Comment by tuapuikia** [comment] 2015-12-11 02:55
Listing time reduce from 6 minutes to 22 seconds.

**Comment by msh100** [comment] 2015-12-25 14:39
@yadayada this is a fantastic improvement, thank you for spending time addressing this.

I am happy for this issue to be closed as I personally believe this is now suitable for any workload however of course there's always room for improvement (so I guess it depends where you want to draw the line on this issue - please close at your own discretion).

Thanks again and enjoy your holidays!

**Comment by HazCod** [comment] 2015-12-26 10:39
Thank you @yadayada !

**Comment by yadayada** [comment] 2016-01-09 06:39
I'm glad the cache rework is working for you guys.

>of course there's always room for improvement 

I still have the idea of memcaching the absolute nodes paths, but that's not going to happen in the near future. Closing this for now.

**Closed by yadayada** 2016-01-09 06:39 UTC
Labels: enhancement, FUSE
