### ISSUE TITLE
Once every 24 hours I have to Kill acdcli process and remount ACD

### ISSUE THREAD

**Issue by dmb247** [yadayada/acd_cli#409] opened 2016-09-15 00:23 UTC
So, this has been going on since I started using acdcli to mount my ACD. 

Basically the issue is that you cannot sync, upload or anything else of the sort. Database locked errors are output along with many lines of directories, most of which are in the Python folder. 

When you look at the processes running, there are always two instances of and_cli running. This is all the time. If I kill both processes and mount my ACD with `acdcli mount -ao ~/rtorrent/downloads/.acd,` two instances begin to run every time. 

it works fine for 18-24 hours, then I start getting the database locked errors. I've attempted to remove the script and start from the beginning, but that didn't seem to do anything either, or I did something wrong in attempting to remove it. 

To get everything running again, I run
`ps xu | grep acdcli | grep -v grep | awk '{ print $2 }' | xargs kill -9`
`acdcli umount ~/rtorrent/downloads/.acd`
`acdcli mount -ao ~/rtorrent/downloads/.acd`

Any ideas what might be causing these issues and what I can do to stop having to run these commands every day?

**Comment by yadayada** [comment] 2016-09-16 04:28
Maybe read the FAQs...

**Comment by dmb247** [comment] 2016-09-16 09:14
I've ready the FAQ and the issue regarding two instances of and_cli causing a database lock. My point in posting this is to say that simply mounting my ACD causes two instances of ACD with two different PIDs to launch. This happens upon mounting the drive, immediately, and after 18-24 hours, i have to kill those processes and remount the drives to see the files. 

So should I have no expectation that the Fuse mount will stay online more than 24 hours at a time?

**Comment by yadayada** [comment] 2016-09-17 13:08
There should not be more than one process running unless the automatic synchronization is turned on (which is not recommended). To be more precise, the autosync process should terminate immediately if the sync interval is 0.

Anyway, I think this is a duplicate of #290.

**Closed by yadayada** 2016-09-17 13:08 UTC
