### ISSUE TITLE
sqlite3.OperationalError - wal mode

### ISSUE THREAD

**Issue by dschense** [yadayada/acd_cli#514] opened 2017-01-15 09:49 UTC
I have two machines running Arch Linux.
Both of them running the same Version:
`acdcli version
acd_cli 0.3.2, api 0.9.0 `

`Python 3.6.0`

On one machine everything is working normal. init, sync, ls, upload, download. Its working.
But on the other machine, the first acdcli sync is working, but the second and avery other command results in:

`Traceback (most recent call last):
  File "/usr/bin/acd_cli", line 11, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/bin/acd_cli.py", line 1574, in main
    cache = db.NodeCache(CACHE_PATH, SETTINGS_PATH, args.check)
  File "/usr/lib/python3.6/site-packages/acdcli/cache/db.py", line 78, in __init__
    self._execute_pragma('journal_mode', self._conf['sqlite']['journal_mode'])
  File "/usr/lib/python3.6/site-packages/acdcli/cache/db.py", line 88, in _execute_pragma
    c.execute('PRAGMA %s=%s;' % (key, value))
sqlite3.OperationalError: cannot change into wal mode from within a transaction`

any body who knows what the problem is?!

**Comment by yadayada** [comment] 2017-01-15 10:08
Duplicate of #509.

**Closed by yadayada** 2017-01-15 10:08 UTC
