### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by TheDrunkenDribbler** [yadayada/acd_cli#501] opened 2016-12-14 09:05 UTC
```
[brontes ~] .local/bin/acd_cli upload -x 2 -r 4 --deduplicate ~/private/pendingmovement/ /PlexCloudSync/
16-12-14 09:04:17.153 [ERROR] [acd_cli] - Traceback (most recent call last):
  File "/media/sdaj1/dribbler/.local/bin/acd_cli.py", line 255, in wrapped
    ret_val = f(*args, **kwargs)
  File "/media/sdaj1/dribbler/.local/bin/acd_cli.py", line 470, in upload_file
    nodes = [n for n in cache.path_format(nodes)]
  File "/media/sdaj1/dribbler/.local/bin/acd_cli.py", line 470, in <listcomp>
    nodes = [n for n in cache.path_format(nodes)]
  File "/media/sdaj1/dribbler/.local/lib/python3.5/site-packages/acdcli/cache/format.py", line 186, in path_format
    yield self.first_path(node.id) + node.name
  File "/media/sdaj1/dribbler/.local/lib/python3.5/site-packages/acdcli/cache/query.py", line 274, in first_path
    node = Node(r)
  File "/media/sdaj1/dribbler/.local/lib/python3.5/site-packages/acdcli/cache/query.py", line 78, in __init__
    self.id = row['id']
TypeError: 'NoneType' object is not subscriptable

[                         ]   0.0% of   14GiB  0/1     0.0B/s       0s
1 file(s) failed.
```

Any fix to this?

Thanks

**Comment by yadayada** [comment] 2016-12-15 15:39
I think this is a duplicate of #417.

**Closed** 2016-12-15 15:39 UTC
Labels: duplicate
