### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by gebn** [yadayada/acd_cli#422] opened 2016-09-24 16:05 UTC
I occasionally receive this error during an upload:

	16-09-21 18:51:58.835 [ERROR] [acd_cli] - Traceback (most recent call last):
	  File "/.../bin/acd_cli.py", line 246, in wrapped
		ret_val = f(*args, **kwargs)
	  File "/.../bin/acd_cli.py", line 461, in upload_file
		nodes = [n for n in cache.path_format(nodes)]
	  File "/.../bin/acd_cli.py", line 461, in <listcomp>
		nodes = [n for n in cache.path_format(nodes)]
	  File "/.../lib/python3.5/site-packages/acdcli/cache/format.py", line 186, in path_format
		yield self.first_path(node.id) + node.name
	  File "/.../lib/python3.5/site-packages/acdcli/cache/query.py", line 274, in first_path
		node = Node(r)
	  File "/.../lib/python3.5/site-packages/acdcli/cache/query.py", line 78, in __init__
		self.id = row['id']
	TypeError: 'NoneType' object is not subscriptable

Explicitly clearing the cache and syncing beforehand doesn't appear to help.

Python 3.5.2
acd_cli 0.3.2

**Comment by yadayada** [comment] 2016-10-02 10:25
Seems to be a duplicate of #417.

**Closed by yadayada** 2016-10-02 10:25 UTC
Labels: cache, duplicate
