### ISSUE TITLE
Token expired

### ISSUE THREAD

**Issue by TheFuzz4** [yadayada/acd_cli#326] opened 2016-05-20 16:11 UTC
Starting today I"m getting a ton of token expired errors and these [CRITICAL] [acd_cli] - Sync failed.  I've attempted several times at removing the database files and actually the whole cache dir but not sure what the cause is.

Also seeing these

16-05-20 16:10:53.854 [WARNING] [acdcli.api.backoff_req] - Waiting 151.093117s because of error(s).

**Comment by saqebakhter** [comment] 2016-05-20 16:12
I'm seeing similar errors - i even generated a new token but it has expired now as well.

**Comment by TheFuzz4** [comment] 2016-05-20 16:14
Well I'm glad to hear that its not just me

**Comment by saqebakhter** [comment] 2016-05-20 16:15
Yeah - not to sure what the deal is maybe they are invalidating tokens from acd_cli ...

**Comment by TheFuzz4** [comment] 2016-05-20 16:22
That would be most unfortunate if thats the case.

**Comment by saqebakhter** [comment] 2016-05-20 17:05
Seems to be okay now ....

**Comment by TheFuzz4** [comment] 2016-05-20 17:17
I'm still getting sync failed errors and the 401 error even with a new oauth file

**Comment by drakeapps** [comment] 2016-05-20 17:19
Yup having the same issue. Happened yesterday, generated a new token and worked until this morning. New token worked for about an hour and then broke again.

**Comment by geekcroft** [comment] 2016-05-20 17:48
Count me in as someone having issues too :/

acd_cli sync seems to work, however any file I try to read from the mounted drive is 0 bytes, and I can't write to it either.

Going to clear cache, remount and resync and see what that ends up like :)

**Comment by TheFuzz4** [comment] 2016-05-20 18:07
@geekcroft Yeah I tried that today with no love

**Comment by geekcroft** [comment] 2016-05-20 18:08
@TheFuzz4 seems to have worked for me, but I suspect it's a bit up/down atm.

Maybe Amazon are having issues, or maybe they are indeed looking to block acd_cli :/

**Comment by cashman04** [comment] 2016-05-20 18:27
I'm getting the same:
```
Getting changesRequestError: 401, [acd_api] no body received.
16-05-20 14:25:07.353 [CRITICAL] [acd_cli] - Sync failed.
```

**Comment by TheFuzz4** [comment] 2016-05-20 19:00
Its working now for me

**Comment by andrwmorph** [comment] 2016-05-20 19:39
Same issue here. I'm only able to upload for about an hour before I have to grab a new oauth token. 

Getting a 401 from https://cdws.us-east-1.amazonaws.com/drive/v1/nodes
reply: 'HTTP/1.1 401 Unauthorized\r\n'

**Comment by combwizard** [comment] 2016-05-20 19:48
Yeah. Same here. Whenever I grab a new oauth token (I use my own security profile, not the appspot one) it now expires after 3600 seconds (used to be 1 month). I'll bring my server down until whatever is causing this works itself out, since it completely messes up my Plex database.

**Comment by andrwmorph** [comment] 2016-05-20 19:52
I tried running a sync after about 20 minutes (without grabbing a new token) and it worked. Perhaps I'm triggering a rate limit and getting temporarily blocked.

**Comment by combwizard** [comment] 2016-05-20 19:57
It's odd though, any token that I request only lasts for 3600 seconds. I tried grabbing the appspot one and I get the same issue:

`16-05-20 21:54:28.604 [INFO] [acdcli.api.oauth] - New token expires at 2016-05-20 22:51:41.476846.`

Which is an hour from requested. I wonder if this is directly related to the issues in this thread, it seemingly started at exactly the same time.

**Comment by combwizard** [comment] 2016-05-20 20:08
@andrwmorph If you look inside your .cache/acd_cli/oauth_data when does the token expire?

**Comment by TheFuzz4** [comment] 2016-05-20 20:12
yep mine expires in 3600

**Comment by TheFuzz4** [comment] 2016-05-20 20:14
and as soon as I put the new token in there, life is good again for now

**Comment by combwizard** [comment] 2016-05-20 20:16
Yeah it looks like the 3600 is normal, I just looked at a backed up token from a month ago and it says the same. Sorry for leading anyone down the wrong road.

**Comment by TheFuzz4** [comment] 2016-05-20 20:17
lol hell if there was a way to do a curl with this to just download directly from amazon I'd totally go that route with a cron to just have it update the token every 30 mins or so

**Comment by AMorporkian** [comment] 2016-05-20 20:22
Reading the logs, it really looks like this is on Amazon's end. It's expiring tokens before the appointed time. I'm locally going to try adjusting the fudge factor in oauth.py so it tries to renew it 15 minutes before it expires and see if that resolves it.

**Comment by andrwmorph** [comment] 2016-05-20 20:31
To be fair you can use curl to get a new one:

`curl https://tensile-runway-92512.appspot.com/ -d "refresh_token=$(grep refresh ~/.cache/acd_cli/oauth_data | cut -d'"' -f4)"`

**Comment by AMorporkian** [comment] 2016-05-20 21:21
Doesn't look like getting it 20 minutes early was enough. I had a new token time out within 11 minutes of getting it. It has to be a server by server thing, I just don't see what else it could be.

**Comment by andrwmorph** [comment] 2016-05-20 21:27
I'm gonna try running this every few minutes to halve the token's expiration time to 1800:

    #!/bin/bash
    OAUTH=~/.cache/acd_cli/oauth_data
    if grep '"expires_in": 3600,' $OAUTH; then
            EXP=$(grep exp_time $OAUTH | grep -Po "\d{10}")
            sed "/exp_time/s/$EXP/$(($EXP-1800))/;/expires_in/s/3600/1800/" $OAUTH
    fi

**Comment by tomwitt2** [comment] 2016-05-20 22:04
Not meaning to poke fun, but what are you hoping to accomplish here?

I ask because I've resigned myself to the fact that I have ONE HOUR to 
accomplish a file transfer using ACD.  It's been this way from the 
start.  As a fan of the Patriots (make your comments, I'm immune), I've 
been trying to move higher resolution copies of games to ACD and 
inevitably they fail.  Comcast (in NH) gives me an effective 1.5MBs 
upload rate.   Anything that can't be transferred within an hour, at 
that rate, doesn't make it to my Cloud Drive account.

**Comment by schmorrison** [comment] 2016-05-20 22:15
I have been using a VPS for my transfers and I receive a "Token has expired" only minutes after it being issued. I have never had a transfer that lasted an entire hour so being unable to sync for more than a couple minutes really drags the effectiveness of this program into the mud.

I have been able to list the files in my drive with a key that previously received a 401 for expiry, only a portion were able to enumerate before I received another 401 for expiry.

**Comment by andrwmorph** [comment] 2016-05-20 22:26
The current issue appears to be that the oauth tokens are getting invalidated early by the server. I decided to try halving the expiration time to see if I could force acd_cli to auto-refresh it every 30 minutes. 

>  Not meaning to poke fun, but what are you hoping to accomplish here?
> 
> I ask because I've resigned myself to the fact that I have ONE HOUR to
> accomplish a file transfer using ACD.  It's been this way from the
> start.  As a fan of the Patriots (make your comments, I'm immune), I've
> been trying to move higher resolution copies of games to ACD and
> inevitably they fail.  Comcast (in NH) gives me an effective 1.5MBs
> upload rate.   Anything that can't be transferred within an hour, at
> that rate, doesn't make it to my Cloud Drive account.

**Comment by tomwitt2** [comment] 2016-05-20 22:31
A stupid question: Currently, does a token refresh mid-transfer impact 
the transfer?

I salivate on answer to this question... no, seriously, my keyboard is 
drool covered and my dog has been office banished for the last 3 hours.

**Comment by safusu** [comment] 2016-05-20 22:39
Ok, thank god it's not happening to just me. 

Will using a security profile resolve this (hopefully temporary) issue?

**Comment by combwizard** [comment] 2016-05-20 22:42
> Will using a security profile resolve this (hopefully temporary) issue?

I use a security profile and I have the same issue.

**Comment by AMorporkian** [comment] 2016-05-20 23:49
@andrwmorph Any like with your cronned script?

**Comment by andrwmorph** [comment] 2016-05-21 00:26
Not really. acd_cli sync sees that the token expired early and grabs a new one but the ongoing upload operation keeps failing with the token expired error.

**Comment by KingPin** [comment] 2016-05-21 02:59
hmmm been trying to fix this for a while now, good thing it isnt just me....

**Comment by AMorporkian** [comment] 2016-05-21 04:01
I can confirm that for my use case, @andrwmorph's script is a good workaround, so thank you for that. My server is on gigabit and rarely has to upload files more than 10 gigs though, so I don't run into the situations where it exceeds the expiration token. Here's the script in context.

```
#!/bin/bash

OAUTH=~/.cache/acd_cli/oauth_data

while true
do
    echo "Uploading...";
    acdcli upload /home/plex_user/cache/* /;
    echo "Syncing...";
    acdcli sync;
    if grep '"expires_in": 3600,' $OAUTH; then
        EXP=$(grep exp_time $OAUTH | grep -Po "\d{10}")
        sed -i "/exp_time/s/$EXP/$(($EXP-1800))/;/expires_in/s/3600/1800/" $OAUTH
    fi
    echo "Sleeping..."
    sleep 60;
done

```

So, for any of you on decently fast connections, run something similar to that in the background and you should be solid. For everyone else, hopefully amazon gets their shit together soon.

**Comment by suprimex** [comment] 2016-05-21 09:48
Same issue here.

**Comment by combwizard** [comment] 2016-05-21 10:00
> For everyone else, hopefully amazon gets their shit together soon.

Yeah, it's unfortunately not useful to me since I don't use ACD for backup, and need near constant read access to my ACD drive via acd_cli. Needless to say my entire setup is entirely hosed for the time being :) I've had so many issues that I think even _if_ this issue gets sorted I'm going to have to find an alternate solution. ACD + acd_cli just isn't stable enough for my purposes.

**Comment by yadayada** [comment] 2016-05-26 13:46
Just a few things...

These 401 errors seem to be intermittent, i.e. doing a ACD request using the *same* token may fail once ("Token has expired."), just to work again later with the following request. 

There is no guarantee that fetching a new token will fix this.

>A stupid question: Currently, does a token refresh mid-transfer impact
the transfer?

If you use multiple upload threads, an already running upload should have used a valid token at the time it was started. A token refresh won't affect it.

Also, an upload that takes longer than an hour will not experience a (real) token timeout. It's a Schroedinger's cat situation; it's deemed to succeed or fail, but you cannot know until it's completed.

**Comment by yadayada** [comment] 2016-07-24 06:28
I assume this is no longer an issue.

**Closed by yadayada** 2016-07-24 06:28 UTC
Labels: API

**Comment by geekcroft** [comment] 2016-07-24 18:19
I'm just running it with the foreground switch and it's fine - but if I
mount it headless it bombs out.

**Comment by zenjabba** [comment] 2016-07-24 20:42
I've found that if I run the following in /etc/rc.local

umount /mnt/amazon
screen -S acdcli -d -m /usr/local/bin/acd_cli -nl --utf --check="none" mount -fg --allow-other /mnt/amazon

it will run basically forever without any major problems.

**Comment by thedarkman41** [comment] 2016-07-24 20:55
I haven't seen this error in a while, but I found that this command could refresh the token for me:

curl https://tensile-runway-92512.appspot.com/ -d "refresh_token=$(grep refresh ~/.cache/acd_cli/oauth_data | cut -d'"' -f4)" | tee ~/.cache/acd_cli/oauth_data

You could use a redirect instead of tee there, and also substitute in the path where you keep your oauth_data file.
