### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Keeperjoey** [yadayada/acd_cli#555] opened 2017-05-01 01:39 UTC
```
17-05-01 03:35:19.337 [ERROR] [acd_cli] - Traceback (most recent call last):
  File "/usr/local/bin/acd_cli.py", line 299, in wrapped
    ret_val = f(*args, **kwargs)
  File "/usr/local/bin/acd_cli.py", line 514, in upload_file
    nodes = [n for n in cache.path_format(nodes)]
  File "/usr/local/bin/acd_cli.py", line 514, in <listcomp>
    nodes = [n for n in cache.path_format(nodes)]
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/format.py", line 186, in path_format
    yield self.first_path(node.id) + node.name
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/query.py", line 281, in first_path
    node = Node(r)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/query.py", line 84, in __init__
    self.id = row['id']
TypeError: 'NoneType' object is not subscriptable
```
I keep getting this error and I have no clue hot to fix it clearing cache does not help....

Ubuntu 16.04
ACDCLI 0.3.2
python 3.5

**Comment by yadayada** [comment] 2017-05-01 05:44
Duplicate of #417.

**Closed by yadayada** 2017-05-01 05:44 UTC
Labels: duplicate
