### ISSUE TITLE
acd_cli cache not updated after a failed upload

### ISSUE THREAD

**Issue by jorti** [yadayada/acd_cli#487] opened 2016-11-17 14:52 UTC
I've noticed that after a failed upload, subsequent retries fail because of a name collision.
If I sync again, I can find the file and see that it has been created, then I trash it and can upload it again.

So it looks like an entry in the local cache should be added after a failed upload, or maybe even auto-trash the file, because the file has been created in ACD, but the content is truncated.

Look at this duplicity bug report, where I paste the exact errors.

https://bugs.launchpad.net/duplicity/+bug/1640195

I use duplicity which calls acd_cli to upload the files. In this example, the command that failed was:

```
acd_cli upload --force --overwrite '/tmp/duplicity-9DdCo1-tempdir/duplicity-inc.20161101T221724Z.to.20161108T061533Z.vol466.difftar.gpg' '/Backups/xenon/duplicity/'
```

In the first attempt, it failed with this error:

```
 BackendException: Error running 'acd_cli upload --force --overwrite '/tmp/duplicity-9DdCo1-tempdir/duplicity-inc.20161101T221724Z.to.20161108T061533Z.vol466.difftar.gpg' '/Backups/xenon/duplicity/'': returned 8, with output:
[ ] 0.0% of 200MiB 0/1 -70.1MB/s 0s
1 file(s) failed.

16-11-08 14:32:50.630 [ERROR] [acd_cli] - Uploading "duplicity-inc.20161101T221724Z.to.20161108T061533Z.vol466.difftar.gpg" failed. RequestError: 1000, HTTPSConnectionPool(host='content-eu.drive.amazonaws.com', port=443): Read timed out. (read timeout=60).

Attempt 1 failed. BackendException: Error running 'acd_cli upload --force --overwrite '/tmp/duplicity-9DdCo1-tempdir/duplicity-inc.20161101T221724Z.to.20161108T061533Z.vol466.difftar.gpg' '/Backups/xenon/duplicity/'': returned 8, with output:
[ ] 0.0% of 200MiB 0/1 -70.1MB/s 0s
1 file(s) failed.
```

The next retries were all failing with a name collision error:

```
 BackendException: Error running 'acd_cli upload --force --overwrite '/tmp/duplicity-9DdCo1-tempdir/duplicity-inc.20161101T221724Z.to.20161108T061533Z.vol466.difftar.gpg' '/Backups/xenon/duplicity/'': returned 1, with output:
[#########################] 100.0% of 201MiB 1/1 15.4MB/s 0s
1 file(s) failed.

16-11-08 14:33:36.932 [ERROR] [acd_cli] - Uploading "duplicity-inc.20161101T221724Z.to.20161108T061533Z.vol466.difftar.gpg" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
16-11-08 14:33:36.988 [WARNING] [acd_cli] - Return value error code: 256.
```

The versions used are:

```
$ python3 -c 'import platform as p; print("%s\n%s" % (p.python_version(), p.platform()))'
3.5.2
Linux-4.8.6-300.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five

$ rpm -q acd_cli
acd_cli-0.3.2-2.fc25.noarch
```

**Comment by ganlub** [comment] 2016-12-13 08:10
Exactly the same situation here, any thoughts on that?

**Comment by yadayada** [comment] 2016-12-13 20:58
I think this is a duplicate of #349.

**Closed** 2016-12-18 16:53 UTC
Labels: CLI
